import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    paddingBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrButton: {
    backgroundColor: '#00C04B',
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  glow: {
    padding: 3,
    borderRadius: 50,
    backgroundColor: 'rgba(0, 255, 0, 0.1)',
    shadowColor: '#0f0',
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 5,
    zIndex: 8,
  },
  blackRectangle: {
    position: 'absolute',
    top:-60,
    left: 0,
    right: 0,
    height: 81,
    backgroundColor: '#333333',
    zIndex: 5,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    position: 'absolute',
    zIndex: 20,
    top: -100,
  },
  clipboardButton: {
    backgroundColor: 'tansparent',
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatbotButton: {
    backgroundColor: 'tansparent',
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clipboardContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 30,
      marginTop: 30,
    },
    chatbotContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 30,
      marginTop: 30,
    },
      chatbotText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: 'bold',
      },
      clipboardText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: 'bold',
      },
});
